name: Run tests

# Run this workflow whenever something new is pushed.
on: push
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest
    
      - uses: actions/checkout@v3
      - name: Retrieve the secret for IPadres
        with:
          CD_SECRET: ${{ secrets.CD_SECRET }}
        run: |
          echo $CD_SECRET
        run: |
          example-command "$PASSWORD_ROOT" 

      - uses: actions/checkout@v3
      - name: Retrieve the secret Password
        with:
          PASSWORD_ROOT: ${{ secrets.PASSWORD_ROOT" }}
        run: |
          example-command $PASSWORD_ROOT
