name: run secrets

#run secrets after run-pipeline has runned
on: 
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Retrieve the secret for IPadres
        run: echo $CD_SECRET

      - name: Retrieve the secret Password
        run: echo $PASSWORD_ROOT

