name: run secrets

#run secrets after run-pipeline has runned
on: 
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Retrieve the secret for IPadres
      - uses: actions/checkout@v3
        with:
          CD_SECRET: ${{ secrets.CD_SECRET }}
        run: echo $CD_SECRET

      - name: Retrieve the secret Password
      - uses: actions/checkout@v3
        with:
          PASSWORD_ROOT: ${{ secrets.PASSWORD_ROOT" }}
        run: echo $PASSWORD_ROOT

