name: Build and deploy
#run secrets after run-pipeline has runned
on: 
  workflow_run:
    workflows: ["Run tests"]
    types:
      - completed
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: deploy Winc app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir test
            cd test
            git clone git@github.com:Paula-Reisen/CD-assignement.git
            echo 'Deployment succesful to digital ocean'
